services:
  mongodb:
    image: mongo:latest
    ports:
      - "${EXPOSE_DB_PORT:-}:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./backend
    ports:
      - "3030:3030"
    environment:
      - HOSTNAME=${HOSTNAME:-host.docker.internal}
      - PORT=${PORT:-3030}
      - DB_URL=mongodb://mongodb:27017/backend-db
      - FRONTEND_URL=${FRONTEND_URL:-http://host.docker.internal:3000}
      - FC_WORKER_URL=http://fc-worker:8080/2015-03-31/functions/function/invocations
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT:-465}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - AWS_CLIENT_MODELS_BUCKET=${AWS_CLIENT_MODELS_BUCKET:-}
      - AWS_REGION=${AWS_REGION:-}
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_APP_API_URL=${VITE_APP_API_URL:-http://host.docker.internal:3030/}
        - VITE_MATOMO_URL=${VITE_MATOMO_URL:-http://host.docker.internal:7000}
        - VITE_MATOMO_SITE=${VITE_MATOMO_SITE:-1}
    ports:
      - "3000:80"
    depends_on:
      - backend

  fc-worker:
    build: ./FC-Worker
    environment:
      - BACKEND_URL=${BACKEND_URL:-http://host.docker.internal:3030}
    depends_on:
      - backend

volumes:
  mongodb_data:
    name: mongodb_data
  uploads_data:
    name: uploads_data
